apiVersion: apps/v1
kind: Deployment
metadata:
 name:  kubernetes-practica2multm
 namespace: default
spec:
 replicas: 3
 selector:
  matchLabels:
   app: practica2_multm
 template:
  metadata:
   labels:
     app: practica2_multm
  spec:
   containers:
    - name: kubernetes-practica2multm
      image: maindavis/multmatrix_ubuntu:1.0
     