apiVersion: v1
kind: Service
metadata:
  name:  practica2fm-entrypoint
  namespace: default
spec:
  type: NodePort
  selector:
    app: practica2_fm
  ports:
  - port: 3301
    targetPort:  3301
    nodePort: 32001
  externalTrafficPolicy:  Cluster
